name: Run Gradle Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Rename JAR file
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME//\//-}
          BUILD_NUMBER=$GITHUB_RUN_NUMBER

          if ls build/libs/*.jar 1> /dev/null 2>&1; then
            for file in build/libs/*.jar; do
              filename=$(basename "$file")
              new_name="cga-$BRANCH_NAME-$BUILD_NUMBER.jar"
              mv "$file" "build/libs/$new_name"
            done
          else
            echo "No JAR file found in build/libs/"
          fi

      - name: Upload JAR file
        uses: actions/upload-artifact@v4.3.0
        with:
          name: cga-${{ github.ref_name }}-${{ github.run_number }}
          path: build/libs/cga-${{ github.ref_name }}-${{ github.run_number }}.jar
